import type { InternalCase, PublicBriefing } from "./session-case";

type Variant = {
  baseTemplate: 0 | 1 | 2;
  internalCase: Partial<InternalCase>;
  publicBriefing: Partial<Omit<PublicBriefing, "dificuldade">>;
};

// Cada variação troca contexto, fator central, vínculos e briefing, mantendo
// somente o perfil comportamental da família correspondente.
export const scenarioVariants: Variant[] = [
  {
    baseTemplate: 0,
    internalCase: { fator_principal: "luto recente sem rede de conversa percebida", fatores_risco: ["isolamento após perda familiar", "rotina de sono irregular", "culpa persistente"], fatores_protecao: ["sobrinho com quem mantém contato", "vizinha de confiança", "vínculo com grupo religioso comunitário"], contexto: "praça de bairro ao amanhecer, ainda com pouco movimento", vinculos: ["sobrinho adolescente", "vizinha de longa data"], observaveis: ["pessoa adulta sentada em banco", "choro contido", "respostas muito baixas"], ocultas: ["não contou à família como está", "tem medo de preocupar o sobrinho"] },
    publicBriefing: { titulo: "Ocorrência simulada — praça de bairro ao amanhecer", acionamento: "Moradores acionaram apoio após encontrarem uma pessoa adulta chorando sozinha em uma praça ainda pouco movimentada.", contexto_observavel: "A equipe chega ao amanhecer. A praça está calma, com poucos moradores passando. Uma pessoa adulta permanece sentada em um banco, com expressão abatida e respostas baixas aos primeiros contatos.", informacoes_recebidas: ["Uma vizinha relatou que a pessoa chegou cedo e não quis conversar.", "Não há familiares no local no momento.", "O fluxo de pessoas foi mantido distante para preservar a conversa."], observaveis_iniciais: ["choro contido", "postura retraída", "respostas baixas", "atenção preservada"], condicoes_da_cena: ["baixo fluxo de pessoas", "iluminação natural crescente", "apoio discreto", "espaço aberto e tranquilo"], aparencia_observavel: "Pessoa adulta com roupas simples e expressão de cansaço, mantendo postura retraída.", orientacao: "Apresente-se com calma e permita pausas. Trabalhe apenas com o que a pessoa revela." },
  },
  {
    baseTemplate: 0,
    internalCase: { fator_principal: "sensação de fracasso após conflito familiar prolongado", fatores_risco: ["afastamento familiar", "desemprego recente", "desesperança"], fatores_protecao: ["filho adulto que procura contato", "amizade de infância", "histórico de participação esportiva"], contexto: "estacionamento de centro esportivo ao final da tarde", vinculos: ["filho adulto", "amigo de infância"], observaveis: ["pessoa adulta parada junto a um muro", "olhar fixo no chão", "fala lenta"], ocultas: ["evitou atender telefonemas", "sente vergonha de pedir ajuda"] },
    publicBriefing: { titulo: "Ocorrência simulada — centro esportivo ao final da tarde", acionamento: "Um funcionário pediu apoio ao notar uma pessoa adulta isolada no estacionamento após o encerramento das atividades.", contexto_observavel: "A equipe encontra um estacionamento quase vazio no final da tarde. Uma pessoa adulta está junto a um muro, olha para o chão e responde lentamente quando percebe a aproximação.", informacoes_recebidas: ["O funcionário informou que ela recusou água e pediu para ficar sozinha.", "Não há acompanhante identificado.", "A área lateral foi mantida livre para reduzir curiosos."], observaveis_iniciais: ["fala lenta", "olhar baixo", "pouca movimentação", "postura fechada"], condicoes_da_cena: ["local aberto", "baixo ruído", "saídas desobstruídas", "apoio em distância discreta"], aparencia_observavel: "Pessoa adulta com roupas cotidianas, expressão cansada e postura fechada.", orientacao: "Comece sem pressão, apresente-se e ofereça escuta sem julgamento." },
  },
  {
    baseTemplate: 1,
    internalCase: { fator_principal: "perda de moradia iminente e sensação de humilhação", fatores_risco: ["dívidas acumuladas", "rompimento com familiares", "uso episódico de álcool em crise"], fatores_protecao: ["irmão disposto a atender ligação", "experiência anterior de trabalho estável", "cuidado com um cachorro"], contexto: "calçada externa de prédio comercial fechado durante a madrugada", vinculos: ["irmão mais velho", "cachorro que vive com ele"], observaveis: ["pessoa adulta andando em círculos", "fala hostil", "mãos inquietas"], ocultas: ["recebeu aviso de despejo", "não contou ao irmão sobre as dívidas"] },
    publicBriefing: { titulo: "Ocorrência simulada — prédio comercial na madrugada", acionamento: "Um vigilante noturno acionou a equipe após observar uma pessoa adulta andando repetidamente diante de um prédio comercial fechado.", contexto_observavel: "A equipe chega a uma calçada ampla, pouco iluminada e sem fluxo regular. Uma pessoa adulta caminha em círculos, mantém as mãos inquietas e reage de forma defensiva à aproximação.", informacoes_recebidas: ["O vigilante relata que ela recusou contato inicial.", "Não foram localizados acompanhantes.", "O entorno foi mantido livre para evitar exposição."], observaveis_iniciais: ["caminhada repetitiva", "fala defensiva", "mãos inquietas", "atenção à equipe"], condicoes_da_cena: ["baixo movimento", "iluminação artificial", "apoio fora do campo imediato", "área lateral preservada"], aparencia_observavel: "Pessoa adulta com roupas amassadas, expressão irritada e postura defensiva.", orientacao: "Evite confronto. Apresente-se, reconheça o incômodo e convide a pessoa a falar no próprio ritmo." },
  },
  {
    baseTemplate: 1,
    internalCase: { fator_principal: "demissão recente percebida como desvalorização pessoal", fatores_risco: ["isolamento social", "conflito conjugal", "autocrítica intensa"], fatores_protecao: ["filha pequena", "colega de trabalho de confiança", "participação em curso profissional"], contexto: "ponto final de ônibus em noite chuvosa", vinculos: ["filha pequena", "colega de trabalho"], observaveis: ["pessoa adulta em pé sob marquise", "fala ríspida", "olhar alternando para a rua"], ocultas: ["não revelou a demissão à família", "teme decepcionar a filha"] },
    publicBriefing: { titulo: "Ocorrência simulada — ponto final de ônibus em noite chuvosa", acionamento: "Passageiros acionaram apoio após uma pessoa adulta permanecer isolada em um ponto final de ônibus e recusar aproximações.", contexto_observavel: "A equipe chega a um ponto de ônibus coberto, com chuva fraca e pouco movimento. Uma pessoa adulta está sob a marquise, responde de forma ríspida e alterna o olhar entre a rua e a equipe.", informacoes_recebidas: ["Passageiros relataram respostas hostis e curtas.", "Não há acompanhante no local.", "O ponto foi mantido com espaço para conversa sem aglomeração."], observaveis_iniciais: ["fala ríspida", "olhar inquieto", "postura defensiva", "atenção preservada"], condicoes_da_cena: ["chuva fraca", "iluminação pública", "baixo fluxo", "apoio discreto"], aparencia_observavel: "Pessoa adulta jovem com roupas comuns, expressão tensa e postura defensiva.", orientacao: "Mantenha a voz calma, não confronte e permita que a pessoa escolha o ritmo inicial." },
  },
  {
    baseTemplate: 2,
    internalCase: { fator_principal: "medo intenso após interromper acompanhamento em saúde", fatores_risco: ["sono irregular", "isolamento", "desconfiança de pessoas próximas"], fatores_protecao: ["pai que mantém contato", "agente de saúde conhecido", "atividade musical comunitária"], contexto: "corredor de residência coletiva no início da manhã", vinculos: ["pai", "agente comunitário de saúde"], observaveis: ["pessoa adulta encostada à parede", "fala desconexa", "olhar inquieto"], ocultas: ["faltou a consultas recentes", "interpreta a aproximação como punição"] },
    publicBriefing: { titulo: "Ocorrência simulada — residência coletiva pela manhã", acionamento: "Moradores chamaram apoio após perceberem uma pessoa adulta muito assustada e com fala difícil de acompanhar no corredor da residência.", contexto_observavel: "A equipe chega a um corredor silencioso no início da manhã. Uma pessoa adulta está encostada à parede, alterna o olhar entre portas e pontos vazios e responde com frases desconexas.", informacoes_recebidas: ["Moradores pediram que ninguém se aproxime de surpresa.", "Não há familiares dentro do corredor.", "O acesso foi mantido livre e sem curiosos."], observaveis_iniciais: ["fala desconexa", "olhar inquieto", "postura de alerta", "respostas fragmentadas"], condicoes_da_cena: ["corredor iluminado", "baixo ruído", "percurso livre", "apoio à distância"], aparencia_observavel: "Pessoa adulta com aparência cansada e expressão de medo, usando roupas cotidianas.", orientacao: "Use frases curtas, reconheça o medo sem confirmar percepções não compartilhadas e preserve a previsibilidade." },
  },
  {
    baseTemplate: 2,
    internalCase: { fator_principal: "confusão após semanas de privação de sono e medo de punição", fatores_risco: ["interrupção de rotina", "isolamento familiar", "medo persistente"], fatores_protecao: ["tia acolhedora", "vínculo com oficina de artes", "experiência anterior de aceitar cuidado"], contexto: "área comum de condomínio ao entardecer", vinculos: ["tia", "oficina de artes local"], observaveis: ["pessoa adulta sentada no chão", "fala fragmentada", "atenção alternando pelo ambiente"], ocultas: ["evita voltar ao apartamento", "acredita que será repreendida se pedir ajuda"] },
    publicBriefing: { titulo: "Ocorrência simulada — condomínio ao entardecer", acionamento: "Uma moradora acionou apoio após encontrar uma pessoa adulta muito assustada na área comum do condomínio.", contexto_observavel: "A equipe encontra uma área comum tranquila no entardecer. Uma pessoa adulta está sentada no chão, alterna a atenção entre a equipe e o ambiente e responde com frases fragmentadas.", informacoes_recebidas: ["A moradora relata que a pessoa parece não ter dormido.", "Ela pediu uma aproximação lenta e previsível.", "O local foi mantido sem outras pessoas próximas."], observaveis_iniciais: ["fala fragmentada", "olhar alternante", "postura de alerta", "medo aparente"], condicoes_da_cena: ["iluminação regular", "baixo ruído", "espaço livre", "apoio afastado"], aparencia_observavel: "Pessoa adulta com roupas comuns, aparência cansada e expressão apreensiva.", orientacao: "Apresente-se com serenidade, use linguagem simples e não confirme percepções que não são observáveis." },
  },
];
